### ISSUE TITLE
Installation fails on system-wide install on os.x

### ISSUE THREAD

**Issue by ralphschindler** [eliangcs/http-prompt#1]
From the debug log:
```
Cleaning up...
  Removing temporary dir /private/tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1431, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 598, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1836, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/util.py", line 295, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-ZBkEd1-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by eliangcs** [comment]
Did you use `sudo`?

**Comment by georules** [comment]
I had (perhaps) a related problem.  I first did pip install without sudo (whoops) and then did it with sudo and got the following:

```
Collecting http-prompt
Requirement already satisfied (use --upgrade to upgrade): click>=5.0 in /Library/Python/2.7/site-packages (from http-prompt)
Requirement already satisfied (use --upgrade to upgrade): parsimonious>=0.6.2 in /Library/Python/2.7/site-packages (from http-prompt)
Requirement already satisfied (use --upgrade to upgrade): httpie>=0.9.0 in /Library/Python/2.7/site-packages (from http-prompt)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.1.0 in /Library/Python/2.7/site-packages (from http-prompt)
Collecting six>=1.10.0 (from http-prompt)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting prompt-toolkit>=0.60 (from http-prompt)
  Downloading prompt_toolkit-1.0.0-py2-none-any.whl (223kB)
    100% |████████████████████████████████| 225kB 2.2MB/s
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /Library/Python/2.7/site-packages (from httpie>=0.9.0->http-prompt)
Collecting wcwidth (from prompt-toolkit>=0.60->http-prompt)
  Downloading wcwidth-0.1.6-py2.py3-none-any.whl
Installing collected packages: six, wcwidth, prompt-toolkit, http-prompt
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-YTkss5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

**Comment by eliangcs** [comment]
Try deleting the problematic directory and re-install again with `sudo`:

```
sudo rm -rf /tmp/pip-YTkss5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info
sudo pip install http-prompt
```

You may have to change the directory permission with `chmod` if you can't delete it.

**Comment by ralphschindler** [comment]
![1 bash 2016-05-19 09-30-31](https://cloud.githubusercontent.com/assets/76674/15397093/723791ac-1da4-11e6-8119-a6c9d4b9abb4.jpg)

**Comment by eliangcs** [comment]
Try uninstalling six first:

```
sudo pip uninstall six
sudo rm -rf <the problematic egg-info directory>
sudo pip install http-prompt
```

**Comment by ralphschindler** [comment]
I'm not sure what `six` is, but it is definitely the problem. The uninstall script for that package won't run correctly. Is there a way to manually remove six?

**Comment by eliangcs** [comment]
You can go to the site-packages directory and delete all the stuffs related to six. On your Mac computer, the site-packages directory is probably at: `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`

**Comment by ralphschindler** [comment]
Yeah, those files can't be removed/updated b/c they are under the protection of SIP in os.x.  It looks as though I've previously installed `httpie` via homebrew.

**Comment by voidpirate** [comment]
Why not use `--user` when installing? You should never have to run `sudo`.

`pip install http-prompt --user`, this will encapsulate the package only in the user directory, instead of system wide.

**Comment by eliangcs** [comment]
@voidpirate this is a great idea! I'll probably add it in README. I was not aware of `--user` option as I use pyenv and pyenv-virtualenv personally.

**Comment by mikeecb** [comment]
Not sure if solved, but this [pip / OS X error with El Capitan](https://github.com/pypa/pip/issues/3165). A possible [solution from stackoverflow](http://stackoverflow.com/questions/31900008/oserror-errno-1-operation-not-permitted-when-installing-scrapy-in-osx-10-11):

`pip install --ignore-installed six`

**Comment by razmo** [comment]
I had the same issue. The solution of @mikeecb worked for me 👍

**Comment by georules** [comment]
sudo pip install http-prompt --ignore-installed six

worked for me.  I assume the --user option would work in combination with the ignore-installed as well.

**Comment by ralphschindler** [comment]
`--ignore-installed` works. I would add this to the readme. Thanks.

**Comment by eliangcs** [comment]
I'll create an FAQ section and add this to it. 👍
