### ISSUE TITLE
Crash using umlauts in "User-Agent" string.

### ISSUE THREAD

**Issue by duncrow** [eliangcs/http-prompt#104]
$ http-prompt www.orf.at
Version: 0.9.0
http://www.orf.at> User-Agent:"Ö"
Traceback (most recent call last):
  File "/home/user/.local/bin/http-prompt", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/http_prompt/cli.py", line 129, in cli
    execute(text, context, listener=listener)
  File "/home/user/.local/lib/python2.7/site-packages/http_prompt/execution.py", line 522, in execute
    click.secho(str(err), err=True, fg='red')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 166: ordinal not in range(128)

**Comment by eliangcs** [comment]
Fixed in v0.9.1. Thanks for reporting!
