### ISSUE TITLE
http-prompt fails to start

### ISSUE THREAD

**Issue by skmlcd** [eliangcs/http-prompt#118]
Windows 8.1
pip 9.0.1 from c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages (python 3.5)

`pip install http-prompt`

No errors.

`http-prompt httpbin.org`

```
Version: 0.10.1
Traceback (most recent call last):
  File "C:\Users\skmlcd\AppData\Local\Programs\Python\Python35-32\Scripts\http-prompt-script.py", line 11, in <module>
    load_entry_point('http-prompt==0.10.1', 'console_scripts', 'http-prompt')()
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\http_prompt\cli.py", line 131, in cli
    style_class = get_style_by_name(cfg['command_style'])
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\pygments\styles\__init__.py", line 55, in get_style_by_name
    for found_name, style in find_plugin_styles():
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\pygments\plugin.py", line 63, in find_plugin_styles
    yield entrypoint.name, entrypoint.load()
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2303, in load
    return self.resolve()
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\skmlcd\appdata\local\programs\python\python35-32\lib\site-packages\pygments_style_darcula-0.1-py3.5.egg\pygments_style_darcula\__init__.py", line 1, in <module>
ImportError: No module named 'base'
```

`http httpie.org` works.

**Comment by eliangcs** [comment]
@skmlcd it seems that the theme you're using doesn't support Python 3. Either a) use Python 2 or b) use a different theme.

**Comment by skmlcd** [comment]
So I assume I should fix something with pygments, right? I think I did some configuration when trying to use it for Hugo. Any tips how would I fix this issue? If this is my error you can close the issue.

**Comment by eliangcs** [comment]
Try changing your `command_style` in the [config file](http://docs.http-prompt.com/en/latest/user-guide.html#configuration).

**Comment by skmlcd** [comment]
Yeah, changing that config line solved the issue. Thank you.
