### ISSUE TITLE
PyOpenSSLContext has no attribute get_ciphers

### ISSUE THREAD

**Issue by Puxap-3opre** [eliangcs/http-prompt#217]
Ubuntu 20.04, Python 3.8.10
Installed with `pip install --user http-prompt`
Added `"~/.local/bin"` to PATH as suggested by installer.
Rebooted.
Run: `http-prompt`
Crash with:

```
Traceback (most recent call last):
  File "/home/alex/.local/bin/http-prompt", line 5, in <module>
    from http_prompt.cli import cli
  File "/home/alex/.local/lib/python3.8/site-packages/http_prompt/cli.py", line 28, in <module>
    from .contextio import load_context, save_context
  File "/home/alex/.local/lib/python3.8/site-packages/http_prompt/contextio.py", line 8, in <module>
    from .execution import execute
  File "/home/alex/.local/lib/python3.8/site-packages/http_prompt/execution.py", line 13, in <module>
    from httpie.core import main as httpie_main
  File "/home/alex/.local/lib/python3.8/site-packages/httpie/core.py", line 15, in <module>
    from .client import collect_messages
  File "/home/alex/.local/lib/python3.8/site-packages/httpie/client.py", line 24, in <module>
    from .ssl_ import AVAILABLE_SSL_VERSION_ARG_MAPPING, HTTPieCertificate, HTTPieHTTPSAdapter
  File "/home/alex/.local/lib/python3.8/site-packages/httpie/ssl_.py", line 105, in <module>
    DEFAULT_SSL_CIPHERS_STRING = ':'.join(HTTPieHTTPSAdapter.get_default_ciphers_names())
  File "/home/alex/.local/lib/python3.8/site-packages/httpie/ssl_.py", line 85, in get_default_ciphers_names
    return [cipher['name'] for cipher in cls._create_ssl_context(verify=False).get_ciphers()]
AttributeError: 'PyOpenSSLContext' object has no attribute 'get_ciphers'

```

**Comment by Puxap-3opre** [comment]
httpie gives the same error.
