### ISSUE TITLE
DistributionNotFound: six>=1.10.0

### ISSUE THREAD

**Issue by guanhui07** [eliangcs/http-prompt#22]
Traceback (most recent call last):
  File "/usr/bin/http-prompt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2603, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: six>=1.10.0

**Comment by eliangcs** [comment]
How do you install? Please also provide the installation log.

**Comment by eliangcs** [comment]
Closing as a wontfix until we have more info.
