### ISSUE TITLE
Encoding limited for Python2. Works well in Python3

### ISSUE THREAD

**Issue by jgomo3** [eliangcs/http-prompt#39]
Only in Python2. In Python3 is working great.

Writing any non ascii character (I was writing Jesús, the ú raised the error) in the prompt gives me this error:

    Exception in thread Thread-13:
    Traceback (most recent call last):                                     
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innr
        self.run()                                                         
      File "/usr/lib/python2.7/threading.py", line 754, in run             
        self.__target(*self.__args, **self.__kwargs)                       
      File "/usr/local/lib/python2.7/dist-packages/prompt_toolkit/interfacn
        completions = list(buffer.completer.get_completions(document, comp)
      File "/usr/local/lib/python2.7/dist-packages/http_prompt/completer.ps
        for comp in match_completions(cur_word, word_dict):
      File "/usr/local/lib/python2.7/dist-packages/http_prompt/completer.ps
        suggestions = fuzzyfinder(cur_word, words)
      File "/usr/local/lib/python2.7/dist-packages/http_prompt/completer.pr
        text = str(text) if not isinstance(text, str) else text
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xfa' in po)

**Comment by leopardpan** [comment]
me too

**Comment by zmjios** [comment]
it is

**Comment by eliangcs** [comment]
Fixed in PR #41. Closed.
