### ISSUE TITLE
malformed URL not handled (unexpected ":")

### ISSUE THREAD

**Issue by wsw70** [eliangcs/http-prompt#76]
When one replaces in an URL  a dot by a colon, an exception is not caught:

```
C:\>http-prompt https://google:com
Version: 0.5.0
Traceback (most recent call last):
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yop\AppData\Local\Programs\Python\Python35-32\Scripts\http-prompt.exe\__main__.py", line 9, in <module>
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\http_prompt\cli.py", line 94, in cli
    load_context(context)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\http_prompt\contextio.py", line 30, in load_context
    filename = url_to_context_filename(context.url)
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\site-packages\http_prompt\contextio.py", line 21, in url_to_context_filename
    port = r.port
  File "c:\users\yop\appdata\local\programs\python\python35-32\lib\urllib\parse.py", line 158, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'com'
```

**Comment by eliangcs** [comment]
Thanks for reporting! This bug was fixed somehow in 0.6.0. Closing.
